name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: vishamay123
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout -B output
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generated Snake" || echo "No changes to commit"
          git push origin output --force
