name: Generate Snake Animation

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: vishamay123
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generated Snake"
          add: "dist/github-contribution-grid-snake.svg"
          branch: output
